services:
  api:
    image: mock-exchange:0.2.0
    container_name: mock-exchange
    env_file:
      - ../apps/mock-exchange/env/dev.env
      - ../apps/mock-exchange/env/dev.worker1.env
    ports:
      - "8000:8000"
    restart: unless-stopped
